version: "3"

services:
  doofmanagerui:
    build:
      context: .
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_RESTAURANT_NAME=${VITE_RESTAURANT_NAME}
      - VITE_RESTAURANT_TIME=${VITE_RESTAURANT_TIME}
    volumes:
      - /root/delivzenmanagerui/dist:/app/dist
