version: "3"

services:
  doof_manager:
    container_name: doof_manager
    build: .
    ports:
      - "5173:5173"
    restart: always
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_RESTAURANT_NAME=${VITE_RESTAURANT_NAME}
